### ISSUE TITLE
Is this line necessary?

### ISSUE THREAD

**Issue by daerty0153** [saurabhprakash/design-patterns#1]
https://github.com/saurabhprakash/design-patterns/blob/ad52db62f216fbdea241034a36b0b775091d3af3/python/observer.py#L67

News is the class which contains an array of observers which trigger get_news of the observer by passing it's instance. I'm not sure if a new News() instance needs to be created here.

**Comment by saurabhprakash** [comment]
Good point, Not needed, will remove

**Comment by saurabhprakash** [comment]
Fixed !!
